instagram/urls.py
from django.contrib import admin
from django.urls import path
from postupload import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',views.IndexView.as_view(),name="index"),
    path('register/',views.Signupview.as_view(),name="registration"),
    path('',views.LoginView.as_view(),name="signin"),
    path('addpost/',views.PostuploadView.as_view(),name="addpost"),
    path('post/<int:id>/',views.PostDetailsView.as_view(),name='addcomment'),
    path('post/comment/add/<int:id>/',views.addcomment_view,name='addcmnts'),
    path('post/<int:id>/like/',views.like_view,name='like'),
    path('image/',views.ProfileView.as_view(),name='images'),
    path('search/',views.SearchbarView.as_view(),name='searchbar'),
    path('accounts/logout/',views.signout_view,name='signout'),
    path("post/<int:id>/remove",views.remove_post,name='remove-post')  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postupload/models.py
from django.db import models

from django.contrib.auth.models import User,AbstractUser


# Create your models here.


class MyUser(AbstractUser):
    phone=models.CharField(max_length=12)
    profile_pic=models.ImageField(null=True,upload_to="profilepics")    

class Postuploads(models.Model):
    user=models.ForeignKey(MyUser,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="images")
    caption=models.CharField(max_length=500)
    post_like=models.ManyToManyField(MyUser,related_name="postlike")
    posted_date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.caption

class Comments(models.Model):
    post=models.ForeignKey(Postuploads,on_delete=models.CASCADE)
    user=models.ForeignKey(MyUser,on_delete=models.CASCADE)
    comment=models.CharField(max_length=200)
    created_date=models.DateField(auto_now_add=True)



    

    

postupload/forms.py
from django import forms
from postupload.models import MyUser
from django.contrib.auth.forms import UserCreationForm

from postupload.models import Postuploads



class RegistrationForm(UserCreationForm):
    class Meta():
        model=MyUser
        fields=['first_name','last_name','username','email',
        'phone','profile_pic','password1','password2']

class LoginForm(forms.Form):                
    username=forms.CharField(widget=forms.TextInput(attrs={"class=col":"form-control","placeholder":"enter username","aria-label":"username"}))      #attrs=attribute
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class=col":"form-control","placeholder":"enter password"}))

class PostuploadForm(forms.ModelForm):
    class Meta():
        model=Postuploads
        fields=['image','caption']

        widgets={
             "image":forms.FileInput(attrs={"class":"form-select mt-5"}),
             "caption":forms.Textarea(attrs={"class":"form-control border border-light mt-5","placeholder":"write a caption...","rows":1})
     
        }

postupload/views.py
from django.shortcuts import render,redirect


# Create your views here.

from django.views.generic import View,TemplateView
from postupload.forms import RegistrationForm,LoginForm,PostuploadForm
from django.views.generic import CreateView,FormView,ListView,DetailView
from postupload.models import MyUser,Postuploads,Comments
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout

class IndexView(ListView):
    template_name="home.html"
    model=Postuploads
    context_object_name='addpost'

    def get_queryset(self):
       return Postuploads.objects.all()

    

class PostuploadView(CreateView):  
    template_name="postupload.html"
    model=Postuploads
    form_class=PostuploadForm
    success_url=reverse_lazy("index")

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)


class PostDetailsView(DetailView):
    model=Postuploads
    template_name='commentdetails.html'
    pk_url_kwarg='id'
    context_object_name='post'

def addcomment_view(request,*args,**kwargs):
    pid=kwargs.get('id')
    post=Postuploads.objects.get(id=pid)
    comment=request.POST.get('cmnts')
    Comments.objects.create(user=request.user,comment=comment,post=post)
    return redirect('index')

def like_view(request,*args,**kwargs):
    id=kwargs.get('id')
    pst=Postuploads.objects.get(id=id)
    pst.post_like.add(request.user)
    pst.save()
    return redirect('index')

class ProfileView(ListView):
    model=Postuploads
    template_name='profile.html'
    context_object_name='images'

    def get_queryset(self):
        return Postuploads.objects.filter(user=self.request.user)

    

class Signupview(CreateView):
    model=MyUser
    form_class=RegistrationForm
    template_name='register.html'
    success_url=reverse_lazy("signin")

class LoginView(FormView):
   form_class=LoginForm
   template_name="login.html"
   success_url=reverse_lazy("signin")
   def post(self,request,*args,**kwargs):
       form=LoginForm(request.POST)
       if form.is_valid():
           uname=form.cleaned_data.get("username")
           pwd=form.cleaned_data.get("password")
           usr=authenticate(request,username=uname,password=pwd)
           if usr:
              login(request,usr)
              return redirect("index")
              
           else:
            return render(request,self.template_name,{"form":form})
            
class SearchbarView(ListView):
    model=Postuploads
    template_name="searchbar.html"


def signout_view(request,*args,**kwargs):
    logout(request)
    return redirect("signin")
   

def remove_post(request,*args,**kwargs):
    id=kwargs.get('id')
    Postuploads.objects.get(id=id).delete()
    return redirect('index')



    

postupload/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>mini insta-instagram.com</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
    <!-- JavaScript Bundle with Popper -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <style>
        h3 {
            font-family: 'Lobster', cursive;
        }
    </style>
</head>

<body>

    <header>
        <!-- nav-bar -->
        <div class="container  fixed-top bg-light">
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4">
                    <div class="container text-center">
                        <div class="row align-items-start">

                            <div class="col col-lg-6 fw-bolder mt-3">
                                <h3>Social media</h3>
                            </div>

                            <div class="col col-lg-4 mt-3">
                             

                                <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    
                                    <a href="{%url 'addpost'%}"><i style="color: black;" class="bi bi-plus-square"></i></h4></a>
                                        
                                </form>
                            </div>
                            <div class="col col-lg-2 mt-3">
                                <h4><i class="bi bi-chat-text"></i></h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-4"></div>
                </div>
            </div>




    </header>
    <div class="container">
        <div class="row">
            {%block body_block%}

            {%endblock%}
        </div>
    </div>
    
    <!-- footer -->
    <div style="height: 9%; ;" class="container fixed-bottom bg-light">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="container text-center">
                    <div class="row align-items-start">

                        <div class="col col-lg-2  mt-3">
                            <a href="{%url 'index'%}"><h3><i style="color: black;" class="bi bi-house-door-fill"></i></h3></a>
                            
                        </div>
                        <div class="col col-lg-2 mt-3">
                            <a href="{%url 'searchbar'%}"><h3><i style="color: black;" class="bi bi-search"></i></h3>                            </a>
                        </div>
                        <div class="col col-lg-4 mt-3">
                            <h4><i class="bi bi-camera-reels"></i></h4>
                        </div>
                        <div class="col col-lg-2 mt-3">
                            <h4><i class="bi bi-heart"></i></h4>
                        </div>
                        <div class="col col-lg-2  mt-3">
                            <a href="{%url 'images'%}"><h3><i style="color: black;" class="bi bi-person-circle"></i></h3></a>
                        </div>
                    </div>
                </div>

                <div class="col-4"></div>

            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>

</body>

</html>

postupload/templates/commentdetails.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>


<body>

    <div class="container mt-5">

        <center>
            <div class="mt-3">
                <h3><strong>Comments</strong></h3>
            </div>
        </center>

        <div style="margin-top: 60px;" class="container">
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4">
                    <div class="accordion accordion-flush" id="accordionFlushExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                             Tap to see all &nbsp;<strong>comments</strong>
                            </button>
                          </h2>
                          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                {%for cmts in post.comments_set.all%}
                                posted by
                                <strong>{{cmts.user}}</strong>&nbsp;&nbsp;{{cmts.comment}}<br><br>{{cmts.created_date}}

                                {%endfor%}                              </div>
                        </div>
                        <form action="{%url 'addcmnts' post.id%}" method="post">
                            {%csrf_token%}

                            <textarea class="form-control mt-5" placeholder="add comment here..." name="cmnts" id=""
                                cols="80" rows="1"></textarea>
                                <div class="row">
                                    <div class="col-4"></div>
                                    <div class="col-4">
                                        <button input type="submit" value="Post" class="btn btn-outline-dark mt-4 col-10">post</button>
                                    </div>
                                    <div class="col-4"></div>
                                </div>

                    </div>
                    </form>
                </div>
                <div class="col-4"></div>
            </div>
        </div>

postupload/templates/home.html
{%extends 'base.html'%}
{%block body_block%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/f6dcf461c1.js" crossorigin="anonymous"></script>

</head>

<body>

</body>

</html>



<div style="margin-top: 60px;" class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%for p in addpost%}

            <div class="col-lg-12">


                <div class="card-body bg-light">
                    <h4 class="card-title"></h4>
                    {%if p.image%}


                    <div class="container">
                        <div class="row">
                            <div class="col-3">
                                <div class="col col-lg-2">
                                    <h7><i class="bi bi-person-circle"></i><strong>({{request.user}})</strong></h7></i>
                                </div>
                            </div>
                            <div class="col-2"></div>
                            <div class="col-5"></div>
                            <div class="col-2">
                                <div class="col col-lg-">
                                    <a href="{%url 'remove-post' p.id%}"><h5><br><i class="bi bi-trash3-fill"></i></h5>
                                    </a>
                                </div>
                            </div>



                            <a href="#!"><img class="card-img-top mb-3" src="{{p.image.url}}" alt="..." /></a>
                            <div class="container">
                                <div class="row align-items-start">

                                    <div class="col col-lg-2">
                                            <a href="{%url 'like' p.id%}"><h3><i style="color: black;" class="fas fa-heart"></i></h3></a>
                                        </Button>
                                    </div>
                                    <div class="col col-lg-2">
                                        
                                        <h3><a href="{%url 'addcomment' p.id%}"><i style="color: black;" class="bi bi-chat-dots"></h3></i></a>
                                        
                                    


                                    <div class="col-4"></div>
                                    
                                </div>
                                
                            </div>
                            <div><span>Liked by &nbsp;<strong>{{p.post_like.all.count}}&nbsp;peoples</strong></span></div>
                            <div>{{p.caption}}</div>

                            {%endif%}


                       
                    {%endfor%}
                </div>
                <div class="col-4"></div>
            </div>

        </div>
        {%endblock%}

postupload/templates/login.html
!
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

   
</head>

<body>
    
    <div style="width:30% ; height: 55%; background-color:rgba(179, 210, 222, 0.297);" class="container border mt-3 ">
    <div>
        <center>
        <div class="row mt-4">
           
            <div><h4 class="fw-bolder text-center"><u>INSTAGRAM</u></h4>
           
            </div>
        </div>
            <div>
           

            <div class="fw-bolder mt-5">

                <form action="" method="post">
                    {%csrf_token%}
                    {{form.as_p}}
                    <input class="btn btn-primary col-10 mt-2" type="submit" value="Log in">
                    <h6 class="text-center mt-2">forgot password?</h6>

                    
                   
                </form>
            </center>
            </div>
            </div>
        </div>
    

</div>
</body>

</html>

postupload/templates/postupload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>


<body>
    <div style="width:50% ; height: 70%; background-color:rgba(170, 219, 220, 0.297);" class="container mt-5 fixed-top">
        <center><h7><i class="bi bi-person-circle"></h7></i>
            <h3 class="mt-3"><u>New Post</u></h3></center>
</body>
</html>

<style>
    h3 {
        font-family: 'Lobster', cursive;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
           
            <form action=""method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <center><input class="btn btn-outline-dark col-10 mt-2" type="submit" value="post"> </center>
           
        </div>
        <div class="col-4"></div>
    </div>
    </form>
</div>

postupload/templates/profile.html
{%extends 'base.html'%}
{%block body_block%}





<div class="container">

    <div class="row" style="margin: 10%;">
        <div class="col-lg-3">
            {%if request.user.profile_pic%}
            <img class="rounded-circle " style="margin-left: 9%;" width="60%" src="{{request.user.profile_pic.url}}">

            {%endif%}

        </div>
        

            <div class="container">
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4">
                        <div><strong><h4>{{request.user}}</h4></strong></div>
                        <div>                        <a href="{%url 'signout'%}">Logout</a></li>
                        </div>



                    </div>
                    <div class="col-4"></div>



                    
                        

                       
                <span class="text-muted ">
                    {{user.first_name}}
                    {{user.last_name}}
                </span>

            
<!-- <div class="container">

    <div class="row" style=" margin: 11%;">
        <hr>

        {%for img in images%}
        <div class="mb-2 col-lg-4" style="height: 330px; width: 330px;">

            <div class="card border-light">
                <div class="card-body card text-bg-dark ">
                    {%if img.image%}

                    <a href="">
                        <img src="{{img.image.url}}" alt="" class="rounded"
                            style="max-height: 330px; min-height: 330px; max-width: 330px; min-width: 330px; ">
                    </a>
                    <div class="card-img-overlay" style="position: fixed-top;">
                        <h5><i class="bi bi-trash3-fill"></i></h5>
                    </div>

                    {%endif%}

                </div>
            </div>

        </div> -->
        <!-- {%endfor%}
    </div>

</div> -->
{%endblock%}

postupload/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <form action="" method="POST" enctype="multipart/form-data">

                    {%csrf_token%}
                    {{form.as_p}}
                    <input type="submit">
                </form>

            </div>
            <div class="col-4"></div>
        </div>
    </div>
</body>

</html>

postupload/templates/searchbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <nav class="navbar bg-light">
                    <div class="container-fluid">
                      <form class="d-flex col-15%" role="search">
                        <input class="form-control me-4 col-10" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                      </form>
                    </div>
                  </nav>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
    
</body>
</html>